### ISSUE TITLE
exports corrupted file on windows

### ISSUE THREAD

**Issue by mrzl** [hamoid/video_export_processing#5] opened 2015-10-28 00:21 UTC
hey abe,
i finally came to check your library, though it's somehow going south. been using this code essentially:

```java
import com.hamoid.*;

VideoExport videoExport;

void setup() {
  size(600, 600);
  videoExport = new VideoExport(this, "basic.mp4");
}
void draw() {
  background(0);
  videoExport.saveFrame();
}
```

it does export a video, which is neither via vlc, nor with ffplay.exe playable:

```java
\bin>ffplay.exe connecting_cities3.mp4
ffplay version N-76278-gd897d4c Copyright (c) 2003-2015 the FFmpeg developers
  built with gcc 5.2.0 (GCC)
[mov,mp4,m4a,3gp,3g2,mj2 @ 000000e574793380] moov atom not found0
connecting_cities3.mp4: Invalid data found when processing input
```

have you seen this before? will try on linux asap, i doubt there will be a problem, though ;)

marcel

**Comment by hamoid** [comment] 2015-10-28 10:01
Hi Marcel!

Which version of Processing are you on? Could you please try different ways of closing your program to see if it makes a difference?

* pressing ESC
* pressing the close button
* pressing the Stop button

I (or we) could try to debug it on your machine when we meet. Thanks for reporting!

**Comment by mrzl** [comment] 2015-10-28 13:59
I tried with 2.2.1 & 3.0.1

I used it only with pressing ESC, as I'm using intellij idea. yeh, letsdoit!

**Comment by mrzl** [comment] 2015-10-28 15:01
tested under ubuntu, works great there.

**Comment by hamoid** [comment] 2016-05-09 09:12
It seems to be a Processing issue: https://github.com/processing/processing/issues/4445

**Comment by hamoid** [comment] 2016-05-09 09:41
Duplicate of #6

**Closed by hamoid** 2016-05-09 09:41 UTC
